import Dexie, { type EntityTable } from 'dexie';
import dexieCloud from 'dexie-cloud-addon';

export interface JournalEntry {
  id?: string; // auto-generated by Dexie Cloud (@id)
  date: string; // YYYY-MM-DD
  rawContent: string;
  content: string; // AI-polished version
  photos: PhotoItem[];
  createdAt: string; // ISO string (JSON-safe for cloud sync)
  updatedAt: string;
}

export interface PhotoItem {
  id: string;
  dataUrl: string; // base64 data URL (syncs via Dexie Cloud JSON)
  thumbnailDataUrl: string;
  filename: string;
  mimeType: string;
}

export interface AppSettings {
  id?: string; // auto-generated by Dexie Cloud (@id)
  settingsKey: string; // 'main'
  lmpDate: string;
  language: 'zh' | 'en';
  notificationsEnabled: boolean;
  aiApiKey: string;
  aiModel: string;
}

const db = new Dexie('BaoziJournal', { addons: [dexieCloud] }) as Dexie & {
  journalEntries: EntityTable<JournalEntry, 'id'>;
  appSettings: EntityTable<AppSettings, 'id'>;
};

db.version(3).stores({
  journalEntries: '@id, date',
  appSettings: '@id, settingsKey',
});

// Configure Dexie Cloud if URL is available
const cloudUrl = typeof window !== 'undefined'
  ? process.env.NEXT_PUBLIC_DEXIE_CLOUD_DB_URL
  : undefined;

if (cloudUrl) {
  db.cloud.configure({
    databaseUrl: cloudUrl,
    requireAuth: false, // app works offline/without login
    customLoginGui: true, // we build our own login UI
  });
}

export { db };

// Helper: get or initialize settings
export async function getSettings(): Promise<AppSettings> {
  let settings = await db.appSettings.where('settingsKey').equals('main').first();
  if (!settings) {
    settings = {
      settingsKey: 'main',
      lmpDate: '2026-01-15',
      language: 'zh',
      notificationsEnabled: false,
      aiApiKey: '',
      aiModel: 'claude-sonnet-4-5-20250929',
    };
    const id = await db.appSettings.add(settings);
    settings.id = id as string;
  }
  // Migrate older settings missing new fields
  if (settings.aiApiKey === undefined) {
    settings.aiApiKey = '';
    settings.aiModel = 'claude-sonnet-4-5-20250929';
    await db.appSettings.put(settings);
  }
  return settings;
}

// Helper: update settings
export async function updateSettings(updates: Partial<AppSettings>) {
  const current = await getSettings();
  await db.appSettings.update(current.id!, updates);
}

// Helper: calculate pregnancy week and day for a given date
export function getPregnancyInfo(lmpDate: string, targetDate: string) {
  const lmp = new Date(lmpDate);
  const target = new Date(targetDate);
  const diffMs = target.getTime() - lmp.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
  const week = Math.floor(diffDays / 7);
  const day = diffDays % 7;
  const dueDate = new Date(lmp);
  dueDate.setDate(dueDate.getDate() + 280);
  const daysUntilDue = Math.floor((dueDate.getTime() - target.getTime()) / (1000 * 60 * 60 * 24));
  return { week, day, diffDays, dueDate, daysUntilDue };
}

// Helper: generate a simple unique id
export function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}

// Helper: compress image file to a base64 data URL
export async function compressImageToDataUrl(
  file: File,
  maxSize: number = 800,
  quality: number = 0.6,
): Promise<string> {
  return new Promise((resolve) => {
    const img = new window.Image();
    const url = URL.createObjectURL(file);
    img.onload = () => {
      const canvas = document.createElement('canvas');
      let { width, height } = img;
      if (width > height) {
        if (width > maxSize) { height = (height * maxSize) / width; width = maxSize; }
      } else {
        if (height > maxSize) { width = (width * maxSize) / height; height = maxSize; }
      }
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d')!;
      ctx.drawImage(img, 0, 0, width, height);
      const dataUrl = canvas.toDataURL('image/jpeg', quality);
      URL.revokeObjectURL(url);
      resolve(dataUrl);
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      // Fallback: read as data URL directly
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.readAsDataURL(file);
    };
    img.src = url;
  });
}

// Helper: create a small thumbnail data URL
export async function createThumbnailDataUrl(
  file: File,
  maxSize: number = 200,
): Promise<string> {
  return compressImageToDataUrl(file, maxSize, 0.5);
}
