import { Language } from './i18n';

export interface WeekData {
  week: number;
  babySize: { zh: string; en: string };
  babyLength: string; // approximate length
  babyWeight: string; // approximate weight
  development: { zh: string; en: string };
  momChanges: { zh: string; en: string };
  tips: { zh: string; en: string };
  emoji: string;
}

// Comprehensive pregnancy data for weeks 1-40
const weeklyData: WeekData[] = [
  {
    week: 1,
    babySize: { zh: '还在准备中', en: 'Getting ready' },
    babyLength: '-',
    babyWeight: '-',
    development: { zh: '这周是月经期，身体正在为怀孕做准备。', en: 'This is your period week. Your body is preparing for pregnancy.' },
    momChanges: { zh: '月经期间，子宫内膜正在脱落更新。', en: 'During your period, the uterine lining is shedding and renewing.' },
    tips: { zh: '开始服用叶酸，保持健康的生活方式。', en: 'Start taking folic acid and maintain a healthy lifestyle.' },
    emoji: '🌱',
  },
  {
    week: 2,
    babySize: { zh: '还在准备中', en: 'Getting ready' },
    babyLength: '-',
    babyWeight: '-',
    development: { zh: '卵子正在成熟，准备排卵。', en: 'The egg is maturing, preparing for ovulation.' },
    momChanges: { zh: '身体正在准备排卵，可能感到精力充沛。', en: 'Your body is preparing to ovulate. You may feel energetic.' },
    tips: { zh: '继续服用叶酸，注意营养均衡。', en: 'Continue taking folic acid and maintain balanced nutrition.' },
    emoji: '🌱',
  },
  {
    week: 3,
    babySize: { zh: '比针尖还小', en: 'Smaller than a pinpoint' },
    babyLength: '0.1mm',
    babyWeight: '-',
    development: { zh: '受精卵形成了！细胞开始快速分裂。', en: 'The fertilized egg has formed! Cells are dividing rapidly.' },
    momChanges: { zh: '你可能还没有任何感觉，受精卵正在向子宫移动。', en: 'You may not feel anything yet. The fertilized egg is traveling to the uterus.' },
    tips: { zh: '避免接触有害物质，不要吸烟喝酒。', en: 'Avoid harmful substances. No smoking or alcohol.' },
    emoji: '✨',
  },
  {
    week: 4,
    babySize: { zh: '像一粒罂粟籽', en: 'Like a poppy seed' },
    babyLength: '1-2mm',
    babyWeight: '<1g',
    development: { zh: '宝宝（胚胎）已经着床！开始形成胎盘和羊膜囊。神经管开始发育。', en: 'Baby (embryo) has implanted! Placenta and amniotic sac forming. Neural tube developing.' },
    momChanges: { zh: '可能出现着床出血，乳房胀痛，感到疲劳。验孕棒可能已经能测出来了！', en: 'You may have implantation bleeding, breast tenderness, fatigue. A pregnancy test may show positive!' },
    tips: { zh: '确认怀孕后预约第一次产检。继续每天服用叶酸400-800微克。避免生食和未煮熟的食物。', en: 'Schedule your first prenatal visit. Continue 400-800mcg folic acid daily. Avoid raw/undercooked foods.' },
    emoji: '🫘',
  },
  {
    week: 5,
    babySize: { zh: '像一粒芝麻', en: 'Like a sesame seed' },
    babyLength: '2-3mm',
    babyWeight: '<1g',
    development: { zh: '心脏开始跳动！大脑、脊髓和血管系统开始形成。', en: 'Heart starts beating! Brain, spinal cord, and blood vessels begin forming.' },
    momChanges: { zh: '孕吐可能开始，感到恶心和疲倦，情绪波动。', en: 'Morning sickness may begin. Nausea, fatigue, mood swings.' },
    tips: { zh: '少食多餐缓解孕吐，早起前先吃几块饼干。保持充足睡眠。', en: 'Eat small frequent meals to ease nausea. Crackers before getting up. Get plenty of sleep.' },
    emoji: '💗',
  },
  {
    week: 6,
    babySize: { zh: '像一颗小扁豆', en: 'Like a lentil' },
    babyLength: '4-6mm',
    babyWeight: '<1g',
    development: { zh: '面部特征开始形成，包括眼睛和耳朵的雏形。手臂和腿的芽开始出现。', en: 'Facial features forming including eyes and ears. Arm and leg buds appearing.' },
    momChanges: { zh: '孕吐可能加重，乳房更加敏感，尿频。', en: 'Morning sickness may worsen, breasts more sensitive, frequent urination.' },
    tips: { zh: '可以做第一次B超确认胎心和孕囊位置。避免剧烈运动但保持适量活动。', en: 'First ultrasound to confirm heartbeat and location. Avoid intense exercise but stay active.' },
    emoji: '👀',
  },
  {
    week: 7,
    babySize: { zh: '像一颗蓝莓', en: 'Like a blueberry' },
    babyLength: '1cm',
    babyWeight: '<1g',
    development: { zh: '大脑快速发育，手指和脚趾开始分化。肝脏开始产生红细胞。', en: 'Brain growing rapidly. Fingers and toes differentiating. Liver producing red blood cells.' },
    momChanges: { zh: '皮肤可能出现变化，口水增多，对气味敏感。', en: 'Skin changes, excess saliva, sensitivity to smells.' },
    tips: { zh: '避免接触猫砂（弓形虫风险），注意食品卫生。', en: 'Avoid cat litter (toxoplasmosis risk). Pay attention to food hygiene.' },
    emoji: '🫐',
  },
  {
    week: 8,
    babySize: { zh: '像一颗覆盆子', en: 'Like a raspberry' },
    babyLength: '1.5-2cm',
    babyWeight: '1g',
    development: { zh: '所有主要器官已经开始形成。手指和脚趾更加明显，尾巴消失了。', en: 'All major organs have begun forming. Fingers and toes more defined. Tail disappearing.' },
    momChanges: { zh: '子宫开始增大，可能感到腰酸。胸罩可能变紧。', en: 'Uterus growing. You may feel lower back ache. Bra may feel tight.' },
    tips: { zh: '可以开始建立孕期档案。选择舒适的内衣。', en: 'Start your prenatal care file. Choose comfortable undergarments.' },
    emoji: '🍇',
  },
  {
    week: 9,
    babySize: { zh: '像一颗葡萄', en: 'Like a grape' },
    babyLength: '2-3cm',
    babyWeight: '2g',
    development: { zh: '宝宝开始有微小的动作了！骨骼和软骨正在形成。', en: 'Baby making tiny movements! Bones and cartilage forming.' },
    momChanges: { zh: '腰围可能开始增加，情绪波动明显，可能有头痛。', en: 'Waistline may increase. Mood swings noticeable. Possible headaches.' },
    tips: { zh: '穿宽松舒适的衣服，保持心情愉快。可以开始记录孕期日记了！', en: 'Wear loose comfortable clothes. Stay positive. Start your pregnancy journal!' },
    emoji: '🍇',
  },
  {
    week: 10,
    babySize: { zh: '像一颗金桔', en: 'Like a kumquat' },
    babyLength: '3-4cm',
    babyWeight: '4g',
    development: { zh: '所有重要器官已经形成，进入快速生长期。指甲开始生长。', en: 'All vital organs formed. Entering rapid growth phase. Nails starting to grow.' },
    momChanges: { zh: '孕吐可能开始减轻，但疲劳感还在。腹部可能稍微隆起。', en: 'Morning sickness may ease, but fatigue continues. Slight bump may appear.' },
    tips: { zh: '可以做NT检查（颈项透明层超声）。多喝水，注意补充营养。', en: 'NT scan (nuchal translucency) can be done. Drink plenty of water and maintain nutrition.' },
    emoji: '🍊',
  },
  {
    week: 11,
    babySize: { zh: '像一个无花果', en: 'Like a fig' },
    babyLength: '4-5cm',
    babyWeight: '7g',
    development: { zh: '宝宝开始打嗝了！生殖器官开始发育，骨骼变硬。', en: 'Baby hiccuping! Reproductive organs developing. Bones hardening.' },
    momChanges: { zh: '头发和指甲可能长得更快，皮肤可能有光泽。', en: 'Hair and nails may grow faster. Skin may glow.' },
    tips: { zh: '做好孕早期筛查，注意铁和钙的摄入。', en: 'Complete first trimester screening. Pay attention to iron and calcium intake.' },
    emoji: '🥝',
  },
  {
    week: 12,
    babySize: { zh: '像一颗李子', en: 'Like a plum' },
    babyLength: '5-6cm',
    babyWeight: '14g',
    development: { zh: '宝宝的脸看起来更像人类了！骨髓开始造血。反射神经开始发育。', en: 'Face looks more human! Bone marrow producing blood. Reflexes developing.' },
    momChanges: { zh: '🎉 孕早期快结束了！流产风险大大降低。你可能开始感觉好一些了。', en: '🎉 First trimester almost over! Miscarriage risk drops significantly. You may feel better.' },
    tips: { zh: '可以考虑向亲友宣布怀孕喜讯了！做唐氏筛查（如有需要）。', en: 'Consider announcing your pregnancy! Do Down syndrome screening if needed.' },
    emoji: '🫒',
  },
  {
    week: 13,
    babySize: { zh: '像一个柠檬', en: 'Like a lemon' },
    babyLength: '7cm',
    babyWeight: '23g',
    development: { zh: '进入孕中期！宝宝的声带正在形成，指纹已经独一无二。', en: 'Second trimester begins! Vocal cords forming. Fingerprints are unique.' },
    momChanges: { zh: '精力开始恢复，孕吐减轻。小腹更加明显。', en: 'Energy returning, morning sickness easing. Bump more visible.' },
    tips: { zh: '可以开始做适量运动如散步和孕妇瑜伽。注意防晒避免妊娠斑。', en: 'Start gentle exercise like walking and prenatal yoga. Use sunscreen to prevent melasma.' },
    emoji: '🍋',
  },
  {
    week: 14,
    babySize: { zh: '像一个桃子', en: 'Like a peach' },
    babyLength: '8-9cm',
    babyWeight: '42g',
    development: { zh: '宝宝开始做各种表情了！可以皱眉、做鬼脸。头发开始生长。', en: 'Baby making facial expressions! Can frown and grimace. Hair growing.' },
    momChanges: { zh: '孕期的"蜜月期"开始了，你可能感觉精力充沛。', en: 'The "honeymoon" of pregnancy begins. You may feel energetic.' },
    tips: { zh: '享受孕中期的好时光，可以开始规划宝宝房间了。', en: 'Enjoy the second trimester. Start planning the nursery.' },
    emoji: '🍑',
  },
  {
    week: 15,
    babySize: { zh: '像一个苹果', en: 'Like an apple' },
    babyLength: '10cm',
    babyWeight: '70g',
    development: { zh: '宝宝可以感知光线了！虽然眼睛还闭着。腿比胳膊长了。', en: 'Baby can sense light! Eyes still closed. Legs are longer than arms now.' },
    momChanges: { zh: '你可能感到鼻塞或流鼻血（孕期常见）。食欲可能增加。', en: 'You may have nasal congestion or nosebleeds (common). Appetite may increase.' },
    tips: { zh: '注意左侧卧睡姿，有利于胎盘血液循环。补充足够的水分。', en: 'Sleep on your left side for better placental blood flow. Stay hydrated.' },
    emoji: '🍎',
  },
  {
    week: 16,
    babySize: { zh: '像一个牛油果', en: 'Like an avocado' },
    babyLength: '11-12cm',
    babyWeight: '100g',
    development: { zh: '宝宝的听觉系统开始发育，骨骼越来越强壮。可能开始有胎动了！', en: 'Hearing developing. Bones getting stronger. You might start feeling movement!' },
    momChanges: { zh: '你可能第一次感觉到胎动（像蝴蝶扑翅）。子宫约在肚脐下方。', en: 'First fetal movement possible (like butterfly wings). Uterus below navel.' },
    tips: { zh: '做唐氏筛查（中期），关注胎动。开始准备孕妇装。', en: 'Mid-pregnancy Down screening. Notice fetal movements. Get maternity clothes.' },
    emoji: '🥑',
  },
  {
    week: 17,
    babySize: { zh: '像一个梨', en: 'Like a pear' },
    babyLength: '13cm',
    babyWeight: '140g',
    development: { zh: '宝宝开始储存脂肪了！脐带越来越粗壮。可以练习吞咽了。', en: 'Baby storing fat! Umbilical cord thickening. Practicing swallowing.' },
    momChanges: { zh: '身体重心开始改变，可能感到背部不适。', en: 'Center of gravity shifting. You may feel back discomfort.' },
    tips: { zh: '注意保持正确姿势，可以做背部拉伸运动。', en: 'Maintain good posture. Do back stretching exercises.' },
    emoji: '🍐',
  },
  {
    week: 18,
    babySize: { zh: '像一个红薯', en: 'Like a sweet potato' },
    babyLength: '14cm',
    babyWeight: '190g',
    development: { zh: '宝宝可以听到声音了！开始对外界声音有反应。打哈欠、翻滚。', en: 'Baby can hear! Responds to sounds. Yawning and rolling.' },
    momChanges: { zh: '可能出现头晕（体位性低血压），胃口大增。', en: 'Possible dizziness (postural hypotension). Increased appetite.' },
    tips: { zh: '可以开始和宝宝说话了！播放轻柔的音乐。准备做大排畸检查。', en: 'Start talking to baby! Play gentle music. Prepare for anatomy scan.' },
    emoji: '🍠',
  },
  {
    week: 19,
    babySize: { zh: '像一个芒果', en: 'Like a mango' },
    babyLength: '15cm',
    babyWeight: '240g',
    development: { zh: '宝宝的感觉器官快速发育。皮肤表面开始形成保护层（胎脂）。', en: 'Sensory organs developing rapidly. Vernix (protective coating) forming on skin.' },
    momChanges: { zh: '可能出现腿抽筋，尤其在晚上。腹部明显隆起。', en: 'Leg cramps may occur, especially at night. Visible bump.' },
    tips: { zh: '多吃含钙和镁的食物缓解抽筋。适当活动小腿。', en: 'Eat calcium and magnesium-rich foods for cramps. Exercise your calves.' },
    emoji: '🥭',
  },
  {
    week: 20,
    babySize: { zh: '像一根香蕉', en: 'Like a banana' },
    babyLength: '16cm',
    babyWeight: '300g',
    development: { zh: '🎉 恭喜到达孕期一半了！宝宝的皮肤变厚了，开始长出胎毛。', en: '🎉 Halfway there! Baby\'s skin thickening. Lanugo (fine hair) growing.' },
    momChanges: { zh: '肚子越来越大，可能出现妊娠纹。子宫到达肚脐位置。', en: 'Belly growing. Stretch marks may appear. Uterus at navel level.' },
    tips: { zh: '做大排畸B超（20-24周）。开始使用妊娠纹霜。', en: 'Anatomy scan ultrasound (20-24 weeks). Start using stretch mark cream.' },
    emoji: '🍌',
  },
  {
    week: 21,
    babySize: { zh: '像一根胡萝卜', en: 'Like a carrot' },
    babyLength: '27cm',
    babyWeight: '360g',
    development: { zh: '宝宝的动作越来越协调，开始有规律的活动和休息周期。', en: 'Baby\'s movements more coordinated. Developing activity and rest cycles.' },
    momChanges: { zh: '胎动越来越明显，有时能从外面看到肚子动。', en: 'Fetal movements more noticeable. Sometimes visible from outside.' },
    tips: { zh: '开始留意胎动规律。保持适量运动如游泳和散步。', en: 'Start noticing movement patterns. Keep exercising: swimming and walking.' },
    emoji: '🥕',
  },
  {
    week: 22,
    babySize: { zh: '像一个木瓜', en: 'Like a papaya' },
    babyLength: '28cm',
    babyWeight: '430g',
    development: { zh: '宝宝的眼睛已经形成，但虹膜还没有颜色。味蕾正在发育。', en: 'Eyes formed but iris has no color yet. Taste buds developing.' },
    momChanges: { zh: '手脚可能出现肿胀，妊娠纹可能出现。', en: 'Hands and feet may swell. Stretch marks may appear.' },
    tips: { zh: '抬高双脚缓解肿胀，避免长时间站立。补充DHA。', en: 'Elevate feet to reduce swelling. Avoid standing long. Take DHA supplements.' },
    emoji: '🥭',
  },
  {
    week: 23,
    babySize: { zh: '像一个大芒果', en: 'Like a large mango' },
    babyLength: '29cm',
    babyWeight: '500g',
    development: { zh: '宝宝开始快速增重。肺部正在发育，练习呼吸动作。', en: 'Baby gaining weight fast. Lungs developing. Practicing breathing.' },
    momChanges: { zh: '可能出现假性宫缩（布拉克斯顿收缩）。脚部变大。', en: 'Braxton Hicks contractions possible. Feet may grow larger.' },
    tips: { zh: '了解假性宫缩和真宫缩的区别。开始考虑分娩计划。', en: 'Learn to distinguish Braxton Hicks from real contractions. Consider birth plan.' },
    emoji: '🥝',
  },
  {
    week: 24,
    babySize: { zh: '像一个玉米', en: 'Like an ear of corn' },
    babyLength: '30cm',
    babyWeight: '600g',
    development: { zh: '宝宝的肺部开始产生表面活性物质。内耳发育完成，有了平衡感。', en: 'Lungs producing surfactant. Inner ear complete. Baby has balance.' },
    momChanges: { zh: '可能出现妊娠糖尿病筛查时间。皮肤可能发痒。', en: 'Gestational diabetes screening time. Skin may be itchy.' },
    tips: { zh: '做妊娠糖尿病筛查（糖耐量测试）。用保湿霜缓解皮肤瘙痒。', en: 'Gestational diabetes screening (glucose tolerance test). Moisturize for itchy skin.' },
    emoji: '🌽',
  },
  {
    week: 25,
    babySize: { zh: '像一个西葫芦', en: 'Like a zucchini' },
    babyLength: '34cm',
    babyWeight: '680g',
    development: { zh: '宝宝开始有了自己的作息规律。皮肤开始变粉红色。鼻孔打开了。', en: 'Baby developing sleep schedule. Skin turning pink. Nostrils opening.' },
    momChanges: { zh: '可能感到呼吸短促，因为子宫压迫横膈膜。', en: 'May feel short of breath as uterus presses on diaphragm.' },
    tips: { zh: '保持良好坐姿帮助呼吸。可以开始准备待产包了。', en: 'Maintain good posture for breathing. Start preparing hospital bag.' },
    emoji: '🥒',
  },
  {
    week: 26,
    babySize: { zh: '像一颗生菜', en: 'Like a head of lettuce' },
    babyLength: '35cm',
    babyWeight: '760g',
    development: { zh: '宝宝的眼睛开始睁开了！可以看到子宫内的光线。大脑组织增加。', en: 'Baby\'s eyes opening! Can see light inside the womb. Brain tissue increasing.' },
    momChanges: { zh: '睡眠可能变差，可能出现腰痛。', en: 'Sleep may worsen. Back pain possible.' },
    tips: { zh: '用孕妇枕帮助睡眠。考虑参加孕妇课程。', en: 'Use a pregnancy pillow. Consider prenatal classes.' },
    emoji: '🥬',
  },
  {
    week: 27,
    babySize: { zh: '像一颗花菜', en: 'Like a cauliflower' },
    babyLength: '36cm',
    babyWeight: '875g',
    development: { zh: '宝宝可以做梦了！大脑非常活跃，能够睁眼闭眼。', en: 'Baby can dream! Brain very active. Can open and close eyes.' },
    momChanges: { zh: '孕晚期即将开始。可能出现水肿和手脚麻木。', en: 'Third trimester approaching. Swelling and numbness in hands/feet possible.' },
    tips: { zh: '注意休息，减少盐分摄入缓解水肿。最后一个孕中期了！', en: 'Rest well. Reduce salt to ease swelling. Last week of second trimester!' },
    emoji: '🥦',
  },
  {
    week: 28,
    babySize: { zh: '像一颗大茄子', en: 'Like a large eggplant' },
    babyLength: '37cm',
    babyWeight: '1kg',
    development: { zh: '🎉 进入孕晚期！宝宝可以眨眼，有睫毛了。做梦时有REM睡眠。', en: '🎉 Third trimester! Baby can blink, has eyelashes. REM sleep when dreaming.' },
    momChanges: { zh: '可能出现频繁的假性宫缩。呼吸更困难。产检频率增加。', en: 'Frequent Braxton Hicks. Breathing harder. Prenatal visits more frequent.' },
    tips: { zh: '开始数胎动（每天固定时间，一小时内至少10次）。产检改为两周一次。', en: 'Start kick counts (at least 10 in an hour daily). Prenatal visits now biweekly.' },
    emoji: '🍆',
  },
  {
    week: 29,
    babySize: { zh: '像一个南瓜', en: 'Like a butternut squash' },
    babyLength: '38cm',
    babyWeight: '1.1kg',
    development: { zh: '宝宝的骨骼进一步强化，需要大量钙质。肌肉和肺继续成熟。', en: 'Bones strengthening, needs lots of calcium. Muscles and lungs maturing.' },
    momChanges: { zh: '可能出现便秘和痔疮。晚上起夜更频繁。', en: 'Constipation and hemorrhoids possible. More nighttime bathroom trips.' },
    tips: { zh: '多吃高纤维食物，保持充足钙摄入（每天1000mg）。', en: 'Eat high-fiber foods. Maintain calcium intake (1000mg daily).' },
    emoji: '🎃',
  },
  {
    week: 30,
    babySize: { zh: '像一棵大白菜', en: 'Like a cabbage' },
    babyLength: '40cm',
    babyWeight: '1.3kg',
    development: { zh: '宝宝的大脑发育更快了，大脑表面开始出现沟回。开始长更多脂肪。', en: 'Brain developing faster with more wrinkles. Building more fat layers.' },
    momChanges: { zh: '感到更加疲劳，可能出现失眠。肚子明显很大了。', en: 'More fatigue. Insomnia possible. Belly noticeably large.' },
    tips: { zh: '可以开始准备宝宝的东西了（衣服、尿布等）。练习呼吸法。', en: 'Start preparing baby items (clothes, diapers). Practice breathing techniques.' },
    emoji: '🥬',
  },
  {
    week: 31,
    babySize: { zh: '像一个椰子', en: 'Like a coconut' },
    babyLength: '41cm',
    babyWeight: '1.5kg',
    development: { zh: '宝宝的五感全部发育了！可以追踪光线，感受触觉和味道。', en: 'All five senses developed! Can track light, feel touch and taste.' },
    momChanges: { zh: '可能出现漏尿（压力性尿失禁）。乳房可能开始分泌初乳。', en: 'Urinary leakage possible (stress incontinence). Breasts may produce colostrum.' },
    tips: { zh: '做凯格尔运动增强盆底肌。了解母乳喂养知识。', en: 'Do Kegel exercises for pelvic floor. Learn about breastfeeding.' },
    emoji: '🥥',
  },
  {
    week: 32,
    babySize: { zh: '像一个哈密瓜', en: 'Like a cantaloupe' },
    babyLength: '42cm',
    babyWeight: '1.7kg',
    development: { zh: '宝宝的趾甲和指甲完全长好了。开始练习呼吸动作。皮肤不再透明。', en: 'Toenails and fingernails fully grown. Practicing breathing. Skin no longer translucent.' },
    momChanges: { zh: '假性宫缩更频繁。可能出现胃灼热和反酸。', en: 'Braxton Hicks more frequent. Heartburn and acid reflux possible.' },
    tips: { zh: '做第三次B超检查胎位。少食多餐缓解胃灼热。', en: 'Third ultrasound to check baby position. Small frequent meals for heartburn.' },
    emoji: '🍈',
  },
  {
    week: 33,
    babySize: { zh: '像一个菠萝', en: 'Like a pineapple' },
    babyLength: '43cm',
    babyWeight: '1.9kg',
    development: { zh: '宝宝的免疫系统正在发育。骨骼还在硬化（头骨除外，保持柔软便于分娩）。', en: 'Immune system developing. Bones hardening (except skull, stays soft for delivery).' },
    momChanges: { zh: '行动越来越不方便。可能出现手腕疼（腕管综合征）。', en: 'Moving around harder. Carpal tunnel syndrome possible.' },
    tips: { zh: '准备好待产包。了解分娩前兆（见红、破水、规律宫缩）。', en: 'Pack hospital bag. Learn labor signs (bloody show, water breaking, regular contractions).' },
    emoji: '🍍',
  },
  {
    week: 34,
    babySize: { zh: '像一个大蜜瓜', en: 'Like a honeydew melon' },
    babyLength: '45cm',
    babyWeight: '2.1kg',
    development: { zh: '宝宝的肺部几乎成熟了。中枢神经系统继续发育。开始头朝下准备出生。', en: 'Lungs almost mature. Central nervous system developing. Moving head-down for birth.' },
    momChanges: { zh: '可能出现视力模糊（激素影响）。疲劳感加重。', en: 'Blurred vision possible (hormonal). Increased fatigue.' },
    tips: { zh: '注意早产征兆。确认产检医院和路线。', en: 'Watch for preterm labor signs. Confirm hospital and route.' },
    emoji: '🍈',
  },
  {
    week: 35,
    babySize: { zh: '像一个哈密瓜', en: 'Like a honeydew melon' },
    babyLength: '46cm',
    babyWeight: '2.4kg',
    development: { zh: '宝宝的脂肪层在加厚，看起来更圆润了。肾脏完全发育。', en: 'Fat layer thickening, baby looks chubbier. Kidneys fully developed.' },
    momChanges: { zh: '可能感到胎儿"入盆"（下降感）。呼吸可能变得稍微容易些。', en: 'Baby may "drop" (engage in pelvis). Breathing may get slightly easier.' },
    tips: { zh: '产检改为每周一次。了解无痛分娩选项。', en: 'Weekly prenatal visits now. Learn about pain relief options for labor.' },
    emoji: '🍈',
  },
  {
    week: 36,
    babySize: { zh: '像一颗大木瓜', en: 'Like a large papaya' },
    babyLength: '47cm',
    babyWeight: '2.6kg',
    development: { zh: '宝宝吞咽了更多的羊水，肝脏和肾脏在处理废物。胎毛开始脱落。', en: 'Swallowing more amniotic fluid. Liver and kidneys processing waste. Lanugo shedding.' },
    momChanges: { zh: '骨盆压力增加，走路可能像摇摆的鸭子。尿频加重。', en: 'Increased pelvic pressure. Waddling walk. More frequent urination.' },
    tips: { zh: '做GBS（B族链球菌）检测。确认新生儿用品准备就绪。', en: 'GBS test. Confirm newborn supplies are ready.' },
    emoji: '🥭',
  },
  {
    week: 37,
    babySize: { zh: '像一棵瑞士甜菜', en: 'Like a bunch of Swiss chard' },
    babyLength: '48cm',
    babyWeight: '2.9kg',
    development: { zh: '🎉 宝宝已经足月了！如果现在出生也是健康的。继续增加脂肪。', en: '🎉 Baby is full term! Healthy if born now. Still adding fat.' },
    momChanges: { zh: '宫颈可能开始变软和扩张。感觉随时可能分娩。', en: 'Cervix may start softening and dilating. Feeling like labor could start anytime.' },
    tips: { zh: '注意分娩征兆，但不要焦虑。放松心情等待宝宝的到来。', en: 'Watch for labor signs but don\'t stress. Relax and wait for baby.' },
    emoji: '🌟',
  },
  {
    week: 38,
    babySize: { zh: '像一棵韭菜', en: 'Like a leek' },
    babyLength: '49cm',
    babyWeight: '3kg',
    development: { zh: '宝宝的器官全部成熟，准备好出生了！头发可能很茂密。', en: 'All organs mature. Ready for birth! May have lots of hair.' },
    momChanges: { zh: '假性宫缩更频繁、更强烈。可能出现"筑巢本能"想要打扫整理。', en: 'Braxton Hicks more frequent and intense. "Nesting instinct" to clean and organize.' },
    tips: { zh: '确认你的待产包、证件和宝宝物品。保持手机充电。', en: 'Confirm hospital bag, documents, and baby items. Keep phone charged.' },
    emoji: '🌟',
  },
  {
    week: 39,
    babySize: { zh: '像一个小西瓜', en: 'Like a small watermelon' },
    babyLength: '50cm',
    babyWeight: '3.2kg',
    development: { zh: '宝宝继续增加脂肪，胸部更加突出以方便出生后吃奶。', en: 'Still gaining fat. Chest more prominent for nursing after birth.' },
    momChanges: { zh: '可能出现见红（宫颈粘液排出）。等待宫缩的到来。', en: 'May see "bloody show" (mucus plug). Waiting for contractions.' },
    tips: { zh: '区分真假宫缩：真宫缩有规律，间隔越来越短，强度越来越大。', en: 'Distinguish real vs false labor: real contractions are regular, getting closer and stronger.' },
    emoji: '🍉',
  },
  {
    week: 40,
    babySize: { zh: '像一个西瓜', en: 'Like a watermelon' },
    babyLength: '51cm',
    babyWeight: '3.4kg',
    development: { zh: '🎉 预产期到了！宝宝已经完全准备好来到这个世界了！', en: '🎉 Due date! Baby is fully ready to enter the world!' },
    momChanges: { zh: '随时可能分娩！如果还没有动静，医生可能会讨论催产。', en: 'Labor could start anytime! If no signs, doctor may discuss induction.' },
    tips: { zh: '放松心情，不要紧张。很多宝宝在预产期前后两周出生都是正常的。加油！💪', en: 'Stay calm. Many babies are born within 2 weeks of due date. You\'ve got this! 💪' },
    emoji: '🍉',
  },
];

export function getWeekData(week: number): WeekData | null {
  if (week < 1 || week > 40) return null;
  return weeklyData[week - 1] || null;
}

export function getWeekDataLocalized(week: number, lang: Language) {
  const data = getWeekData(week);
  if (!data) return null;
  return {
    week: data.week,
    babySize: data.babySize[lang],
    babyLength: data.babyLength,
    babyWeight: data.babyWeight,
    development: data.development[lang],
    momChanges: data.momChanges[lang],
    tips: data.tips[lang],
    emoji: data.emoji,
  };
}

export function getTrimester(week: number): 1 | 2 | 3 {
  if (week <= 12) return 1;
  if (week <= 27) return 2;
  return 3;
}
